### PR TITLE
Bump RedisGraph

### PR DESCRIPTION
**Pull request by blockchain-art**
bumping RedisGraph to match the version that's on all environments

### CODE REVIEW

**Comment by itskingori** [comment]
You'll need to update CHANGELOG.md file as well. Releasing is manual unfortunately. You could also help us by updating the README.md with a contributing section, which you can copy [from here](https://github.com/Intellection/docker-elasticsearch/tree/7.8.0-1).

**Comment by blockchain-art** [comment]
> You'll need to update CHANGELOG.md file as well. Releasing is manual unfortunately. You could also help us by updating the README.md with a contributing section, which you can copy [from here](https://github.com/Intellection/docker-elasticsearch/tree/7.8.0-1).

What's the correct versioning format, is it based on the RedisGraph version or incremental

**Comment by itskingori** [comment]
Yes, tracks version ... and if the version hasn't changed, we append a `-1` (that you can increment accordingly).

**Comment by blockchain-art** [comment]
@itskingori Need some 👀 I think it's right

**Review by itskingori — APPROVED** [review]

**Pull request merged**
