### PR TITLE
[SRE-2199] Package latest version of Redis Graph into a Docker image

### PR DESCRIPTION
**Pull request by itskingori**
Title says it all.

### References

* https://github.com/RedisGraph/RedisGraph
* https://hub.docker.com/r/redislabs/redisgraph
* https://hub.docker.com/repository/docker/zappi/redis-graph

### CODE REVIEW

**Review by hadrianvalentine — COMMENTED** [review]
Are we adding anything to the image here or will we do that in a separate PR?

**Comment by itskingori** [comment]
Yes. Separate PR.

**Review by hadrianvalentine — APPROVED** [review]

**Comment by itskingori** [comment]
Screenshot 2022-02-17 at 13 58 20

**Review by zacblazic — COMMENTED** [review]
👍🏼

**Pull request merged**
